"""add brand column to products table

Revision ID: ad0c40281ada
Revises: 6864754d65f9
Create Date: 2026-07-13 13:27:15.020960

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ad0c40281ada"
down_revision: str | Sequence[str] | None = "6864754d65f9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("products", sa.Column("brand", sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "brand")
    # ### end Alembic commands ###
